from enum import Enum

class Color(Enum):
    NONE = ...
    BLACK = ...
    WHITE = ...

class Board:
    def __init__(self) -> None: ...
    def get_piece(self, row: int, col: int) -> Color: ...
    def get_black_pieces(self) -> int: ...
    def get_white_pieces(self) -> int: ...
    def count_black_pieces(self) -> int: ...
    def count_white_pieces(self) -> int: ...
    def count_pieces(self) -> int: ...
    def get_valid_moves_mask(self, color: Color) -> int: ...
    def get_flips(self, row: int, col: int, color: Color) -> int: ...
    def apply_move_with_flips(self, row: int, col: int, color: Color, flips: int) -> None: ...
    def make_move(self, row: int, col: int, color: Color) -> None: ...
    def has_any_valid_move(self, color: Color) -> bool: ...
    def is_valid_move(self, row: int, col: int, color: Color) -> bool: ...

class Game:
    def __init__(self) -> None: ...
    def get_board(self) -> Board: ...
    def get_current_player(self) -> Color: ...
    def is_game_over(self) -> bool: ...
    def get_winner(self) -> Color: ...
    def make_move(self, row: int, col: int) -> bool: ...
    def apply_move_fast(self, row: int, col: int) -> None: ...
