from enum import Enum
from typing import List, Tuple

class Color(Enum):
    NONE = ...
    BLACK = ...
    WHITE = ...

def greedy_move(board: Board, color: Color) -> int: ...
def minimax_move(board: Board, color: Color) -> int: ...

class Board:
    def __init__(self) -> None: ...
    def get_piece(self, row: int, col: int) -> Color: ...
    def get_black_pieces(self) -> int: ...
    def get_white_pieces(self) -> int: ...
    def count_black_pieces(self) -> int: ...
    def count_white_pieces(self) -> int: ...
    def count_pieces(self) -> int: ...
    def get_valid_moves_mask(self, color: Color) -> int: ...
    def get_flips(self, row: int, col: int, color: Color) -> int: ...
    def apply_move_with_flips(self, row: int, col: int, color: Color, flips: int) -> None: ...
    def make_move(self, row: int, col: int, color: Color) -> None: ...
    def has_any_valid_move(self, color: Color) -> bool: ...
    def is_valid_move(self, row: int, col: int, color: Color) -> bool: ...

class Game:
    def __init__(self) -> None: ...
    def get_board(self) -> Board: ...
    def get_current_player(self) -> Color: ...
    def is_game_over(self) -> bool: ...
    def get_winner(self) -> Color: ...
    def make_move(self, row: int, col: int) -> bool: ...
    def apply_move_fast(self, row: int, col: int) -> None: ...

class BatchedMCTSEngine:
    def __init__(self, c_puct: float) -> None: ...
    def initialize(self, games: List['Game']) -> None: ...
    def clear_cache(self) -> None: ...
    def prepare_evaluation(self) -> Tuple[List[int], List[int], List[int], List[int]]: ...
    def process_evaluation(self, policies: List[List[float]], values: List[float]) -> None: ...
    def get_action_probs(self, temperature: float) -> List[List[float]]: ...
